Batch3_RealTimeProject/Batch3_RealTimeProject/Controllers/CategoryController.cs
using Batch3_RealTimeProject.DAL.Repository;
using Batch3_RealTimeProject.Models;
using Microsoft.AspNetCore.Mvc;

namespace Batch3_RealTimeProject.Controllers
{
    public class CategoryController : Controller

    {
        private readonly IGenericRepo<Category> _genericRepoCate;
        public CategoryController(IGenericRepo<Category> genericRepoCate)
        {
            _genericRepoCate = genericRepoCate;
        }

        [HttpGet]

        public IActionResult ShowCategoryList()
        {
            var listOfCate = _genericRepoCate.GetAll();
            return View(listOfCate);
        }

        [HttpGet]

        public JsonResult ShowCategoryList1()
        {
            var listOfCate = _genericRepoCate.GetAll();
            return Json(listOfCate);
        }
        //tempdata/ ViewBag/Viewdata
        //Http Verbs

        //what are the different state management techniques in mvc? -- Tempdata/ViewBag/ViewData/Query string/SEssions/Cookies

        //two way binding

        [HttpGet]
        public IActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCategory(Category cate)
        {
            _genericRepoCate.Create(cate);

            TempData["Success"] = "Category Created Successfully";

            return RedirectToAction("ShowCategoryList");
        }
        [HttpGet]
        public IActionResult EditCategory(int id)
        {
            return View(_genericRepoCate.GetById(id));
        }

        [HttpPost]

        public IActionResult EditCategory(Category category)
        {
            _genericRepoCate.Update(category);
            TempData["Success"] = "Category Updated Successfully";
            return RedirectToAction("ShowCategoryList");
        }



        //[HttpGet]

        //public IActionResult Delete(int id)

        //{

        //    _genericRepoCate.DeleteById(id);

        //    return RedirectToAction("ShowCategoryList");

        //}

    }

}

Batch3_RealTimeProject/Batch3_RealTimeProject/Controllers/CompanyController.cs
using Batch3_RealTimeProject.DAL.Repository;
using Batch3_RealTimeProject.Models;
using Microsoft.AspNetCore.Mvc;

namespace Batch3_RealTimeProject.Controllers
{
    public class CompanyController : Controller
    {

        private readonly IGenericRepo<Company> _genericRepoComp;
        public CompanyController(IGenericRepo<Company> genericRepoComp)
        {
            _genericRepoComp = genericRepoComp;
        }

        public IActionResult Index()
        {
            return View();
        }

        // Code to show the list of Companies
        [HttpGet]
        public IActionResult ShowCompanyList()
        {
            var listOfComp = _genericRepoComp.GetAll();
            return View(listOfComp);
        }

        //MVC

        //1) MVC life cycle
        //2) TempData, ViewBag and ViewData -- differnt ways of session management in mvc
        //3) IActionResult and various types
        //4) difference between MVC controller and API Controller
        //5) Error handling in mvc
        //6) filters in mvc - action/authorization/exception/authentication
        //7) can we have multiple layout pages in mvc -- yes but it has to be referred specifically
        //8) can we have multiple models in a view - no no no
        //9) have you used jquery to connect to ui to controller
        //10) Suppose i have a grid, and i would like to refresh the grid data without refreshing the page - AJAX calls
        //public JsonResult GetCompany()
        //{
        //    Company company = new Company();
        //    company.Address = new Address();
        //    company.Address.PhoneNumber = "454654";
        //    company.Address.AddressLine1 = "ABC";
        //    company.CompanyName = "Test";
        //    return Json(company);
        //}

        [HttpGet]
        public IActionResult AddCompany()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCompany(Company comp)
        {
            _genericRepoComp.Create(comp);

            TempData["Success"] = "Company Created Successfully";

            return RedirectToAction("ShowCompanyList");
        }
        [HttpGet]
        public IActionResult EditCompany(int id)
        {
            return View(_genericRepoComp.GetById(id));
        }

        [HttpPost]

        public IActionResult EditCompany(Company company)
        {
            _genericRepoComp.Update(company);
            TempData["Success"] = "Company Updated Successfully";
            return RedirectToAction("ShowCompanyList");
        }
        //[HttpGet]

        //public IActionResult Delete(int id)

        //{

        //    _genericRepoCate.DeleteById(id);

        //    return RedirectToAction("ShowCategoryList");

        //}







    }
}

Batch3_RealTimeProject/Batch3_RealTimeProject/Controllers/ProductController.cs
using Batch3_RealTimeProject.DAL;
using Batch3_RealTimeProject.DAL.Repository;
using Batch3_RealTimeProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Batch3_RealTimeProject.Controllers
{
    public class ProductController : Controller
    {
        private readonly IGenericRepo<Product> _productRepo;
        private readonly IGenericRepo<Category> _categoryRepo;
        private readonly IGenericRepo<ProductImage> _productImageRepo;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IGenericRepo<Product> productRepo, IGenericRepo<Category> categoryRepo,
            IWebHostEnvironment webHostEnvironment, IGenericRepo<ProductImage> productImageRepo)
        {
            _productRepo = productRepo;
            _categoryRepo = categoryRepo;
            _webHostEnvironment = webHostEnvironment;
            _productImageRepo = productImageRepo;
        }


        // GET: ProductController
        [HttpGet]
        public IActionResult ShowProductList()
        {
            var listofproduct = _productRepo.GetAll();
            return View(listofproduct);
        }

        [HttpGet]
        public IActionResult AddProduct()
        {
            //example for projections in EF/ anonymous functions/delegates-anonymous functions/ Projections
            IEnumerable<SelectListItem> CategoryList = _categoryRepo.GetAll().Select(u => new SelectListItem
            {
                Text = u.CategoryName,
                Value = u.CategoryId.ToString()
            });
            ViewBag.CategoryList = CategoryList;
            return View();
        }

        [HttpPost]
        public IActionResult AddProduct(Product product, IFormFile file)
        {
            string wwwRootPath = _webHostEnvironment.WebRootPath;
            if (file != null)
            {
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                string productImagePath = Path.Combine(wwwRootPath, @"Images\Product");

                //what is the purpose using block
                //using statement internally calls IDisposable which will make sure that 
                //the resource that has been consumed during sqlConnectiom, Filestream, or memory stream
                //will be freed up -- GC get invoked
                using (var fileStream = new FileStream(Path.Combine(productImagePath, fileName), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
                product.ProductImageUrl = @"\Images\Product\" + fileName;
            }

            _productRepo.Create(product);
            TempData["Success"] = "Product Created Successfully";
            return RedirectToAction("ShowProductList");
        }

        [HttpGet]
        public IActionResult EditProduct(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var product = _productRepo.GetById(id);
            IEnumerable<SelectListItem> CategoryList = _categoryRepo.GetAll().Select(u => new SelectListItem
            {
                Text = u.CategoryName,
                Value = u.CategoryId.ToString()
            });
            ViewBag.CategoryList = CategoryList;
            if (product == null)
            {
                return NotFound();

            }
            return View(product);

        }

        [HttpPost]
        public IActionResult EditProduct(Product product, IFormFile file)
        {
            string wwwRootPath = _webHostEnvironment.WebRootPath;
            string productImagePath = Path.Combine(wwwRootPath, @"Images\Product");
            var productImage = new ProductImage();
            string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
            if (!String.IsNullOrEmpty(product.ProductImageUrl))
            {
                var oldPath = Path.Combine(productImagePath, product.ProductImageUrl);

                if (System.IO.File.Exists(oldPath))
                {
                    System.IO.File.Delete(oldPath);
                }
                using (var fileStream = new FileStream(Path.Combine(productImagePath, fileName), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
                product.ProductImageUrl = @"\Images\Product\" + fileName;
            }
            productImage.ProductId = product.Id;
            productImage.ImageUrl = product.ProductImageUrl = @"\Images\Product\" + fileName;
            _productImageRepo.Create(productImage);
            _productRepo.Update(product);
            TempData["Success"] = "Product Updated Successfully";
            return RedirectToAction("ShowProductList");
        }

        [HttpGet]
        public IActionResult DeleteProduct(int id)
        {
            var deleteProduct = _productRepo.GetById(id);
            if (deleteProduct == null)
            {
                return NotFound();

            }
            _productRepo.DeleteById(deleteProduct);
            return RedirectToAction("ShowProductList");

        }
    }
}

Batch3_RealTimeProject/Batch3_RealTimeProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Batch3_RealTimeProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Batch3_RealTimeProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.3/css/dataTables.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Batch3_RealTimeProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="ShowProductList">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="ShowCategoryList">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="Index">Companies</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Batch3_RealTimeProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.js"
            integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
            crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/2.0.3/js/dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Batch3_RealTimeProject/Batch3_RealTimeProject/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
    <h2>@TempData["Success"]</h2>
}
@if (TempData["Error"] != null)
{
    <h2>@TempData["Error"]</h2>
}